
import BDplantei.CatalogoDAO;
import java.util.ArrayList;
import java.util.List;
import portalPlantei.Planta;

public class CatalogoPlanta extends javax.swing.JFrame {

        Planta novaPlanta;
        List<Planta> listaPlantas;
    /**
     * Creates new form CatalogoPlanta
     */
    public CatalogoPlanta() {
        initComponents();
        populaPlantas();
        selectPlantasActionPerformed(null);
    }
    
    private void populaPlantas () {
        
        listaPlantas = CatalogoDAO.catalogoDados();
        List<String> listaNomePlanta = new ArrayList<>();
        
        listaPlantas.forEach((item) -> {
            listaNomePlanta.add(item.getNomePlanta());
        });
        
        String[] arrayPlantas = listaNomePlanta.toArray(new String[0]);
        selectPlantas.setModel(new javax.swing.DefaultComboBoxModel<>(arrayPlantas));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtAddPlanta = new javax.swing.JButton();
        txTempoAgua = new javax.swing.JTextField();
        txDescricao = new javax.swing.JTextField();
        txTempoAdubo = new javax.swing.JTextField();
        txTempoSol = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CPvoltar = new javax.swing.JButton();
        selectPlantas = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtAddPlanta.setBackground(new java.awt.Color(204, 204, 204));
        BtAddPlanta.setText("   Adiciona a minhas plantas   ");
        BtAddPlanta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtAddPlanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAddPlantaActionPerformed(evt);
            }
        });

        jLabel2.setText("Descrição");

        jLabel3.setText("Tempo de sol");

        jLabel4.setText(" Rega");

        jLabel5.setText("Tempo de adubo");

        CPvoltar.setBackground(new java.awt.Color(204, 204, 204));
        CPvoltar.setText("voltar");
        CPvoltar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CPvoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CPvoltarActionPerformed(evt);
            }
        });

        selectPlantas.setToolTipText("");
        selectPlantas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectPlantasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CPvoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txTempoSol, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txTempoAdubo, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txTempoAgua, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(selectPlantas, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BtAddPlanta)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jLabel5)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectPlantas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtAddPlanta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txTempoSol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jLabel4)
                .addGap(29, 29, 29)
                .addComponent(txTempoAgua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(txTempoAdubo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(CPvoltar)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtAddPlantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAddPlantaActionPerformed
        CadastraPlanta cadasPlanta = new CadastraPlanta();
        cadasPlanta.prepararCadastro(novaPlanta);
        cadasPlanta.setVisible(true);
    }//GEN-LAST:event_BtAddPlantaActionPerformed

    private void CPvoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPvoltarActionPerformed
        Inicio telainicio = new Inicio();
        telainicio.setVisible(true);

    }//GEN-LAST:event_CPvoltarActionPerformed

    private void selectPlantasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectPlantasActionPerformed

        txDescricao.setText("");
        txTempoSol.setText("");
        txTempoAgua.setText("");
        txTempoAdubo.setText("");
        novaPlanta = new Planta();
        
        for(int i = 0; i < listaPlantas.size(); i++) {
            if(listaPlantas.get(i).getNomePlanta().equals(selectPlantas.getSelectedItem().toString())){
                txDescricao.setText(listaPlantas.get(i).getDescricao());
                txTempoSol.setText(listaPlantas.get(i).getTempoSol());
                txTempoAgua.setText(listaPlantas.get(i).getRega());
                txTempoAdubo.setText(listaPlantas.get(i).getTempoAdubo());

                novaPlanta = listaPlantas.get(i);
                return;
            }
        }
    }//GEN-LAST:event_selectPlantasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CatalogoPlanta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CatalogoPlanta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CatalogoPlanta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CatalogoPlanta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CatalogoPlanta().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAddPlanta;
    private javax.swing.JButton CPvoltar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> selectPlantas;
    private javax.swing.JTextField txDescricao;
    private javax.swing.JTextField txTempoAdubo;
    private javax.swing.JTextField txTempoAgua;
    private javax.swing.JTextField txTempoSol;
    // End of variables declaration//GEN-END:variables
}
